### ISSUE TITLE
Cant get content to show

### ISSUE THREAD

**Issue by jgw96** [PolymerElements/paper-header-panel#16]
The new Polymer Docs show that paper-header-panel can be used like this:
![screenshot 2015-05-31 at 4 14 34 pm](https://cloud.githubusercontent.com/assets/8823093/7903916/34c5d38e-07b0-11e5-8c30-687ffa88befe.png)

When i try to use <paper-header-panel> i can not seem to get the content to show up. I can find the elements using chrome dev tools but they do not seem to be rendering on screen.

Here is my markup:
![screenshot 2015-05-31 at 4 17 05 pm](https://cloud.githubusercontent.com/assets/8823093/7903929/86c58e22-07b0-11e5-9636-89eb52e621cb.png)

Here is a screenshot of that html in the latest chrome

![screenshot 2015-05-31 at 4 02 28 pm](https://cloud.githubusercontent.com/assets/8823093/7903847/7bb21e4e-07ae-11e5-966f-fdac0d103dc5.png)

As you can see the paper-toolbar renders but the content does not.

**Comment by ianchildress** [comment]
I have experienced this same problem in multiple uses. Here is an example where i am using a nested paper-header-panel but the content does not display. If I deselect the overflow-x and overflow-y css settings then they display. Screenshots attached.

![hidden](https://cloud.githubusercontent.com/assets/8595626/8579698/2505340c-2584-11e5-800e-5194d33169e8.png)

![displayed](https://cloud.githubusercontent.com/assets/8595626/8579701/2b2e44ae-2584-11e5-8093-f55cdfd4d8a6.png)
