### ISSUE TITLE
z-index problem in cover mode with toolbar elements

### ISSUE THREAD

**Issue by m4b** [PolymerElements/paper-header-panel#18]
## Description

I'm seeing problems like this when cover mode is set:

![screen shot 2015-06-01 at 3 44 05 pm](https://cloud.githubusercontent.com/assets/1920204/7924017/2ffa8c94-0875-11e5-9c03-8fe05e41442f.png)

I.e., elements in the `<paper-toolbar>` seem to have a higher z-index than the elements of the `<paper-header-panel>`'s body/content, which are supposed to cover elements of the `<paper-toolbar>`.

Going into the `<paper-toolbar>` element and turning off the z-index for the `topBar`, `middleBar`, and `bottomBar` seems to fix this - however, just setting the the z-index of a content element to a large value, or the content section, etc., _does not_ seem to fix it.

I'm not sure of the intent, but it seems like desired behavior for cover mode would include not having to explicitly set z-index values for the content, and/or unset values for the toolbar, since it is understood that content elements should cover elements in the toolbar, hence the name.
## Steps to reproduce:

I can reproduce this in chrome and firefox, on OSX.

The following code sample renders something like the above:

``` html
<link rel="import" href="bower_components/polymer/polymer.html">
<!-- paper -->
<link rel="import" href="bower_components/paper-styles/paper-styles-classes.html">
<link rel="import" href="bower_components/paper-toolbar/paper-toolbar.html">
<link rel="import" href="bower_components/paper-header-panel/paper-header-panel.html">
<dom-module id="dom-1">
  <style>
    paper-toolbar {
      height: 200px;
      color: #ff0000;
    }
    .content {
      margin: 60px;
      background-color: #ffffff;
      z-index: 10000;
    }
  </style>
  <template>
    <paper-header-panel mode="cover">
      <paper-toolbar>
        <div>Much Content</div>
        <div class="bottom">
          I'm more stuff
        </div>
      </paper-toolbar>
      <div class="content">
        <ul>
          <template is="dom-repeat" items="{{_items}}">
            <li><span style="z-index: 1000;">{{item}}</span></li>
          </template>
        </ul>
      </div>
    </paper-header-panel>
  </template>
</dom-module>
<script>
  Polymer({
    is: "dom-1",
    properties: {
      _items : {
        type: Array,
        notify: true,
        value: function () {
          return [
            1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,
            1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,
            1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,
            1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,
            1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
            ];
          }
        }
    }
  });
</script>
```

I can also reproduce the error in polymer-starter-kit by setting the `<paper-header-panel>` to cover mode, and adding some extra cruft so it covers the drawer button, the title, etc.

**Comment by m4b** [comment]
ping.

I still have this issue in every format I've tested; chrome on android, safari on iOS, firefox, chrome, chromium on desktop.

Particularly problematic is mobile safari.  If for example, a `<paper-fab>` is used in the header's content, with a fixed position, etc., it will be covered by the header panel.

I have noticed that setting the `<paper-header-panel>`'s `z-index` to -1 resolves the problem, except then the drawer button is no longer tappable.

**Comment by blasten** [comment]
@m4b this issue is confirmed and moved to https://github.com/PolymerElements/paper-toolbar/issues/24

**Comment by blasten** [comment]
@m4b  This is fixed now in paper-toolbar. Can you update it via `bower update` ?

**Comment by m4b** [comment]
@blasten: confirmed this fixes the original problem (nice work!), however, I have to set the z-index to a large number for the `paper-drawer-toggle` in order to use it/tap it.  Is this desired behavior?  If so, it should at least be documented somewhere, since it's slight unintuitive IMHO.

I've also noticed that a `<paper-header-panel mode="standard">` embedded inside a `<paper-header-panel mode="cover">` has similar z-index issues in _its_ toolbar.  I'm not sure how the top parent can effect the child in this way, but I think it might be residue of a bug still lurking?

Here is a (complicated) jsbin indicating what I mean (**note**, this will only run on chrome):

http://jsbin.com/necevexeno/1/edit

if you remove the cover mode from the `<paper-header-panel>` inside `<height-test>`, then the `<paper-header-panel>` inside of `<nested-panel>` displays fine.  But if you use cover mode, then, it has a similar unusual z-index problem.

Not sure what you want to do, (and the above behavior in the jsbin might be an error on my part) but you might want to re-open the issue?  Of course, it's up to you :)
