### ISSUE TITLE
Styling #mainContainer

### ISSUE THREAD

**Issue by nathanjohnson320** [PolymerElements/paper-header-panel#25]
How do I set a background color on the #mainContainer? I've tried selecting manually in my component but nothing seems to affect it.

Using a deep selector doesn't appear to work either

```
html /deep/ #mainContainer {
    background-color: #d3d3d3;
}
```

**Comment by blasten** [comment]
@nathanjohnson320 you can use: 

``` html
<style is="custom-style">
 paper-header-panel {
   --paper-header-panel-standard-container: {
     background-color: #d3d3d3;
   };
}
</style>
```

if you haven't changed the mode attribute.

**Comment by nathanjohnson320** [comment]
awesome that's exactly what I was looking for
