### ISSUE TITLE
drop shadow graphical layer

### ISSUE THREAD

**Issue by hypnoce** [PolymerElements/paper-header-panel#30]
Hello,

the drop shadow has a css 3D transform thats force the creation of a graphical layer.
I do understand it's necessity when animating the drop shadow, but in standard mode for instance, if the content does not have it's own graphical layer, there is no need to create one for the drop shadow.

Besides animation, am I missing any other use case that needs the 3d-transformed drop shadow ?

Thanks

**Comment by blasten** [comment]
The transform is used for `waterfall-*` modes. The shadow needs to grow so that's why it uses the transform.
