### ISSUE TITLE
Element interferes with ripple effect on paper-icon-button and paper-toggle-button

### ISSUE THREAD

**Issue by AndrewBarfield** [PolymerElements/paper-header-panel#32]
Regarding:
- Polymer v1.0.5, Build Time: 2015-07-23T16:07:08-0700
- paper-header-panel, v1.0.3, commit 7226d1f4d1

If I add this element to my application it 'stunts' or 'mutes' the ripple effect on paper-icon-button and paper-toggle-button. What appears is a quick flicker in the background around the button.

This can be resolved in one of two ways:

1) **Temporary runtime solution:** Close the paper-drawer-panel by reducing the window width. As odd as it may sound, yes, closing the drawer panel allows the ripple animation to return.

2) **Permanent solution:** Remove the paper-header-panel import: `<link rel="import" href="bower_components/paper-header-panel/paper-header-panel.html">`. Ripple animations perform as expected with the drawer panel open or closed.

**Comment by blasten** [comment]
hmm Are you also using a paper-drawer-panel as well?  it sounds like this issue: https://github.com/PolymerElements/paper-drawer-panel/pull/52  Can you check if it works in Firefox?

**Comment by AndrewBarfield** [comment]
I'm using both the paper-drawer-panel and paper-header-panel. Just this morning I found removing this old CSS fixes the problem:

``` ...
div [drawer],
div [main] {
 overflow-y: auto;
}
...
```

I was using DIVs before switching to paper-header-panel. I'll call this one "user-error". Thanks for the help and link!
