### ISSUE TITLE
Does not hide android-chrome address bar when scrolling

### ISSUE THREAD

**Issue by Everlag** [PolymerElements/paper-header-panel#36]
Polymer/core-header-panel/issues/15 is a holdover from core-header-panel.

> A core-toolbar inside of core-header-panel is pinned to the top of the page when scrolling, but the address bar doesn't auto-hide. the polymer-project website works, but they appear to use their own custom components. core-scroll-header-panel also exhibits this same issue.

A potential fix was presented at https://github.com/google/material-design-lite/issues/1072#issuecomment-123445135 for the material design lite project.

**Comment by blasten** [comment]
Yes, we know about this limitation. `position:fixed` has a lot of limitations too. The good news is that we are working on a solution for the "main" app header that will use `position:fixed`. cc @frankiefu

**Comment by Ajedi32** [comment]
@robrez FYI, there's a button for that over on the right (under Notifications). :arrow_upper_right:

**Comment by blasten** [comment]
We have a new experimental set of layout elements https://github.com/PolymerLabs/app-layout that aim to solve this issue. This experimental set of elements will be soon released as carbon elements along with new elements for routing and internationalization. Check it out!
