### ISSUE TITLE
Newer Chrome is not respecting paper-header-panel Styling Api While Older Chromium is

### ISSUE THREAD

**Issue by dman777** [PolymerElements/paper-header-panel#41]
I'm pretty sure this issue is with Polymer in general, but just in case I wanted to reference this since it deals with `paper-header-panel`

https://github.com/Polymer/polymer/issues/2307

**Comment by blasten** [comment]
Can you try the latest release ?  `bower update` or https://github.com/PolymerElements/paper-header-panel/releases/tag/v1.0.4
