### ISSUE TITLE
[Feature Request] paper-footer-panel or property to switch header to bottom

### ISSUE THREAD

**Issue by xmakro** [PolymerElements/paper-header-panel#42]

**Comment by bipin-nag** [comment]
I want pages to have both header and footer. So I guess a `paper-footer` class in the toolbar like already present `paper-header` will solve this. I can't find where paper-header is defined though.

**Comment by blasten** [comment]
You can already achieve this if you use the app-layout elements.  https://github.com/PolymerLabs/app-layout although we don't have formally have a`app-footer` yet. Should there be one? @frankiefu ?
