### ISSUE TITLE
the header has incorrect size

### ISSUE THREAD

**Issue by frankiefu** [PolymerElements/paper-header-panel#5]
Running the demo on Chrome Beta, the header has the incorrect size.

![screen shot 2015-05-04 at 10 45 43 am](https://cloud.githubusercontent.com/assets/116360/7458704/6ada9b82-f24b-11e4-9380-baa163ee04e9.png)

**Comment by notwaldorf** [comment]
Hmm, that's alarming. It looks fine on Stable and Canary:
![screen shot 2015-05-04 at 11 34 03 am](https://cloud.githubusercontent.com/assets/1369170/7459530/88169344-f251-11e4-9b52-0aeff140915b.png)

**Comment by frankiefu** [comment]
On Canary 44.0.2391.0, the scrolling on the content under the header doesn't work.  Same problem on Firefox too.  FWIW, core-header-panel (0.5) works fine on Canary and Firefox.

**Comment by blasten** [comment]
This has been fixed by adding `flex-basis: 0.0001px;`

https://github.com/PolymerElements/paper-header-panel/blob/89f7c17b32ba8ff0e2f4cc5cd216eb5a88fa3d1b/paper-header-panel.html#L125
