### ISSUE TITLE
paper-header-panel tall mode animation has no time curve

### ISSUE THREAD

**Issue by dman777** [PolymerElements/paper-header-panel#50]
from [Google Design Animation](https://www.google.com/design/spec/animation/authentic-motion.html#authentic-motion-mass-weight)

> Use curved motion and avoid linear spatial paths. Identify the qualities of motion best suited to your object, and represent their motion accordingly. Curves represent that change over time, for a particular value range. Find a curve that fits that character of motion you are describing.

This is not the case when the mode in the paper header panel animation goes from tall to standard and vice versa. The time curve is incorrectly linear.

**Comment by blasten** [comment]
There could be a custom property to customize the easing fn.

**Comment by blasten** [comment]
@dman777 I just noticed that the user can set the easing function directly. https://github.com/PolymerElements/paper-header-panel/blob/master/demo/index.html#L40 e.g.

``` css
transition-timing-function: ease-in-out;
```

Therefore, I'm closing this issue.
