### ISSUE TITLE
Could you make a new release?

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-header-panel#56]
There are already many new changes. Personally, I need in a project. :sweat_smile:

Could you make a new release? Thanks!

**Comment by femiadeyemi** [comment]
I second @abdonrd request. Please make a new release.

**Comment by notwaldorf** [comment]
Done! 1.1.0 has been released.

**Comment by abdonrd** [comment]
Yay! Thanks @notwaldorf! :smiley:
