### ISSUE TITLE
Remove old branches

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-header-panel#58]
I think that we can remove the old [branches](https://github.com/PolymerElements/paper-header-panel/branches):
- `0.8-preview`
- `blasten-patch-1` (already merged)
- `mainpanel-overflow` (already closed)

**Comment by blasten** [comment]
Good call, I just removed them.

**Comment by abdonrd** [comment]
@blasten I think you have forgotten `mainpanel-overflow`. :sweat_smile:
