### ISSUE TITLE
Changing the default scroll bar in all browsers

### ISSUE THREAD

**Issue by nagababji123** [PolymerElements/paper-header-panel#59]
Hai,

Is their any element in polymer that is used for custom scroll bar styles for all browsers(changing default scroll and add my own scroll bar).
or
How can i do this?
I am using to change the scroll bar of paper-header-panel
Any help is appreciate,
Thank you,
Babji﻿

**Comment by blasten** [comment]
Not exactly, but you can take a look at this post https://css-tricks.com/custom-scrollbars-in-webkit/.  You can definitely use these pseudo elements in combination with `paper-header-panel` or `paper-scroll-header-panel`.

**Comment by GeoloeG-IsT** [comment]
@blasten there is no mixin to target this specifically, and you cannot break encapsulation (apart from the /deep/ usage that will be deprecated). Same issue for [iron-autogrow-textarea #60](https://github.com/PolymerElements/iron-autogrow-textarea/issues/60)
