### ISSUE TITLE
/deep/ combinator is deprecated

### ISSUE THREAD

**Issue by platinumindustries** [PolymerElements/paper-header-panel#70]
paper-header-panel is still using the deprecated /deep/ combinator, please update.

**Comment by abdonrd** [comment]
This was fixed by @blasten here: https://github.com/PolymerElements/paper-header-panel/pull/9.

**Comment by notwaldorf** [comment]
@platinumindustries please make sure you're using the latest version, and let me know if this is still happening. Looks fixed.

**Comment by platinumindustries** [comment]
looks like a mistake, chrome (Version 47.0.2526.111) is throwing errors in the console log and complaining about line 482 in paper-header-panel.html.
This is the line:

``` javascript
    this._setAtTop(main.scrollTop === 0);
```

Why's that?

**Comment by Lange** [comment]
I'm seeing the same thing as @platinumindustries; my DevTools console warns about `paper-header-panel` using `/deep/`, but the line it is complaining about is the one in @platinumindustries's post. I am using Chrome 48.0.2564.116 on Windows 10.

**Comment by Sunny2720** [comment]
I too am seeing this issue with Version 56.0.2924.87 (64-bit) chrome. This warning occurred after I added paper-search-bar to my page.
