### ISSUE TITLE
Contents in paper-header-panel is getting overlaped in chrome

### ISSUE THREAD

**Issue by sujith3g** [PolymerElements/paper-header-panel#75]
I've got a paper-header-panel inside body. content fits 100% below the header(added fit class). In **chrome (version 48.*)** the divs inside the content div are getting overlapped because of height getting automatically set to 0px. Everything was working fine before **chrome 48.**\* update. I've checked in Firefox, opera and safari and the page is working as expected. If I resize the window everything gets fixed. I assume this is because of the iron-resize-behavior. I can solve this by manually setting the height for each inner div.

.
[here](http://jsbin.com/dohunojono/edit?html,output) is the JsBin link

``` html

<body class="fullbleed layout vertical">

  <paper-header-panel class="flex">
    <paper-toolbar>
      <div>Hello World!</div>
    </paper-toolbar>
    <div class="fit layout vertical">
        <div class="horizontal layout">
          <div class="flex">Item One left</div>
          <div>Item One right</div>
        </div>
        <div class="horizontal layout">
          <div class="flex">Item Two left</div>
          <div>Item Two right</div>
        </div>
    </div>
 </paper-header-panel>


</body>

```
## Output in firefox

<img width="640" alt="screen shot 2016-02-05 at 3 22 42 pm" src="https://cloud.githubusercontent.com/assets/1298779/12843024/a374bd6e-cc1c-11e5-947d-8d002f91d515.png">
## Output in chrome 48.0.2564.97 (64-bit)

<img width="639" alt="screen shot 2016-02-05 at 3 23 04 pm" src="https://cloud.githubusercontent.com/assets/1298779/12843016/94646eb4-cc1c-11e5-9c1c-9e5391575ed0.png">

**Comment by hedcet** [comment]
i have the same issue [here](https://github.com/HedCET/TorrentAlert/blob/master/.polymer/linto/layout-inbox.html#L149)

that forced me to use paper-item instead of div [here](https://github.com/HedCET/TorrentAlert/blob/master/.polymer/linto/layout-inbox.html#L138)

how i solve this issue in chrome 48.\* ?

**Comment by aruntk** [comment]
@HedCET paper-item works fine because they have explicitly defined the height of the paper-item. Any element with height explicitly defined would work.

**Comment by frankiefu** [comment]
Seems to be working fine in Chrome 48.0.2564.109 (64-bit)

**Comment by sujith3g** [comment]
:+1: Its working :)

**Comment by frankiefu** [comment]
Awesome!
