### ISSUE TITLE
Nested paper-header-panel not showing content

### ISSUE THREAD

**Issue by Borengar** [PolymerElements/paper-header-panel#76]
A paper-header-panel inside a paper-header-panel won't show its content.  
[Example JSBin](https://jsbin.com/xihequwifu/edit?html,output)  
![Example image](https://cloud.githubusercontent.com/assets/5701614/12955769/df84a3b2-d024-11e5-8a68-5da58a4e5046.png)  
Disabling overflow-x and overflow-y styles on '#mainContainer' shows the content.

**Comment by frankiefu** [comment]
You should use `fit` to make the content fit to the main area.  e.g. https://jsbin.com/lukiqovupa/edit?html,output

**Comment by Borengar** [comment]
Using `fit` did the trick. Thanks.  
It's kind of strange that it still displays the `paper-toolbar` of the nested `paper-header-panel` but nothing else. And in the screenshot it looks like the content is taking up space where it should without displaying anything.

**Comment by frankiefu** [comment]
In your original jsbin, `paper-toolbar` has an explicit height set on it so it displays correctly.  The `#mainContainer` is actually has 0 height and with `overflow: auto` and so the content inside is not being shown.
