### ISSUE TITLE
paper-header-panel does not display any content when Doctype is specified

### ISSUE THREAD

**Issue by jollycopper** [PolymerElements/paper-header-panel#77]
The following code does not display any content on Chrome, as long as <!Doctype html> is specified. If doctype declaration is removed then it works fine.

The following code is written in Jade, but it is equivalent to pure html.

``` jade
body(class="fullbleed layout vertical")
  paper-header-panel(class="flex" mode="waterfall")
    paper-toolbar
      paper-icon-button(icon="menu")
      span(class="title")= title
    div(class="content fit") content fits 100% below the header
```

**Comment by jollycopper** [comment]
What I found pretty funny is that even the demo on polymer-project.org is not working [1]. As you can see the content is not showing below the toolbar.

[1]. https://elements.polymer-project.org/guides/assets/tall-header.html

**Comment by blasten** [comment]
iron-flex-layout.html doesn't import the CSS classes anymore. You can either import `iron-flex-layout/classes/iron-flex-layout.html` manually or use mixins.

**Comment by jollycopper** [comment]
The same question on stackoverflow:

http://stackoverflow.com/questions/34660221/polymer-paper-header-panel-not-showing-any-content-in-paper-drawer-panel

**Comment by Storyyeller** [comment]
Why is this closed? The Polymer examples still don't work in Chrome.

**Comment by blasten** [comment]
@Storyyeller the demos are in https://elements.polymer-project.org/elements/paper-header-panel?view=demo:demo/index.html&active=paper-header-panel
