### ISSUE TITLE
inconsistent event "content-scroll"

### ISSUE THREAD

**Issue by alfalabs** [PolymerElements/paper-header-panel#83]
### Description

`<paper-header-panel>` and `<paper-scroll-header-panel>` share event named `content-scroll`
In supplied example, this event fires while using `<paper-scroll-header-panel>` but not with `<paper-header-panel>`
The problem is not with event not firing in `<paper-header-panel>` (there is another way to get this event) but the need to write different code for each header-panel.

Also filed under: https://github.com/PolymerElements/paper-scroll-header-panel/issues/97
Related issue: https://github.com/PolymerElements/paper-header-panel/issues/84
### Expected outcome

Events named with the same name should have consistent behavior. The web components inside these panels should have the same code to handle scrolling - to be reusable in both.
### Actual outcome

Different code has to be written for each panel type.
### Live Demo

example with `paper-scroll-header-panel` - event is firing - please see console.
https://jsbin.com/yigeciyomo/edit?html,console,output

example with `paper-header-panel` - event not firing - please see console for lack of message.
https://jsbin.com/miyuluxojo/edit?html,console,output

**Comment by blasten** [comment]
closing since this issue was answered in https://github.com/PolymerElements/paper-scroll-header-panel/issues/97
