### ISSUE TITLE
Animate the height change in the toolbar - missing .animate?

### ISSUE THREAD

**Issue by bwh-rl** [PolymerElements/paper-header-panel#93]
### Description

As far as i understood the docu, the paper-header-panel should give the paper-toolbar the .animate class for animated height changes, and height changes should be always animated.

> When inside a paper-header-panel element, the class .animate is toggled to animate the height change in the toolbar.

But if the size classes for the toolbar are changed, the height is not animated. This is because the .animate class is not always set by the paper-header-panel (inside the _modeChanged function).

If this is the correct behavior, please update the docu and descripe how the .animate can be activated.
### Expected outcome

Animation
### Actual outcome

No animation
### Live Demo

https://jsbin.com/pomadahuzi/edit?html,output
### Browsers Affected
- Chrome (since the class is missing i guess every browser is affected, but i only tested chrome)

**Comment by blasten** [comment]
You can add `mode="waterfall-tall"` or manually add the following CSS to the header:

``` css
 paper-toolbar {
  animate: height 0.2s
}
```

Note that animating on height can cause bad performance.
