### ISSUE TITLE
async load broken in chrome

### ISSUE THREAD

**Issue by s-trooper** [PolymerElements/paper-header-panel#94]
Hi,  if i load this element like this:

``` html
<link rel="import" href="/shared/polymer/bower_components/paper-header-panel/paper-header-panel.html" async>
<link rel="import" href="/shared/polymer/bower_components/paper-toolbar/paper-toolbar.html" async>
```

i get an error in chrome but not FF:

```
paper-header-panel.html:396 Uncaught TypeError: Cannot read property 'headerContent' of undefined
```
### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by blasten** [comment]
It seems like `$` is undefined. I can't reproduce in the demos. Would you mind attaching a jsbin or repro steps in the issue?

**Comment by s-trooper** [comment]
I confirm that in a demo async import work as expected, the problem persists in our app still but I assume we have a bug in our code. I close this issue, sorry for trouble.
