### ISSUE TITLE
Demo is totally borked on Safari 10

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-header-panel#95]
Go to https://elements.polymer-project.org/elements/paper-header-panel?view=demo:demo/index.html&active=paper-header-panel on Safari 10 (iOS)

**Comment by frankiefu** [comment]
From the console:

```
[Error] TypeError: undefined is not an object (evaluating 'descriptor.value')
    installProperty (webcomponents.js:235)
    registerInstanceProperties (webcomponents.js:182)
    registerInternal (webcomponents.js:269)
    register (webcomponents.js:260)
    (anonymous function) (webcomponents.js:4365)
    Global Code (webcomponents.js:4367)
```

webcomponetsjs issue: https://github.com/webcomponents/webcomponentsjs/issues/617

**Comment by frankiefu** [comment]
Oh wait, the webcomponentsjs issue is in ShadowDOM polyfill, which this demo shouldn't be using.  Currently the demo is incorrectly loading `webcomponents.js`, instead it should load `webcomponents-lite.js`
